// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbetqwmrajuucthndinv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxiZXRxd21yYWp1dWN0aG5kaW52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMjU0MjIsImV4cCI6MjA2OTkwMTQyMn0.PyAL1Gl4Iqba3LlhfZAeCihgt8fRhuIYZwLTTMzw2oo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});